### ISSUE TITLE
Is there a chance to change the number of attempts count...?

### ISSUE THREAD

**Issue by rakeshpalivela** [tabrindle/cordova-plugin-samsungpass#2]
Hi,

The plugin was working fine. But, I need to do some customization on two things.
1. Number of attempts : Currently the finger print attempts was 5 times. Is there any change to increase or decrease the attempts.?
1. Custom message on Popup : In popup I want to change the message "Swipe your finger to unlock...."  to my own text.

Please provide the solution for this....

**Comment by tabrindle** [comment]
Hello, glad you like the plugin. This is not an active project, but feel free to make a PR.

**Comment by Anita03** [comment]
Hi,

I am not able to get backup password field while implementing this fingerprint plugin.
Please help.
