### ISSUE TITLE
Failure on Redmi Note 3

### ISSUE THREAD

**Issue by DazChong** [tabrindle/cordova-plugin-samsungpass#4]
Model number: `Redmi Note 3`
Android version: `5.1.1 LMY47V`
Android security patch level: `2016-02-01`
MIUI version: `MIUI Global 7.1 | Stable 7.1.8.0(LHOMICL)`

I assume this plugin only support Samsung phones?

**Comment by tabrindle** [comment]
Yes, this is for samsung phones only.
